### ISSUE TITLE
tests fail on python 3.6.3, passes on python 2.7

### ISSUE THREAD

**Issue by sjsrey** [pec27/smerfs#1]
On 3.6.3:
```
s/smerfs - [master] » nosetests tests/
EE
======================================================================
ERROR: Failure: SyntaxError (Missing parentheses in call to 'print'. Did you mean print(int max_imag, asym)? (test_extremes.py, line 21))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/serge/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/serge/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/serge/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/serge/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/serge/anaconda3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/serge/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serge/Dropbox/s/smerfs/tests/test_extremes.py", line 21
    print max_imag, asym
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int max_imag, asym)?
```

On 2.7
```
(pysal2) s/smerfs - [master] » nosetests tests/
..........
----------------------------------------------------------------------
Ran 10 tests in 1.949s

OK
(pysal2) s/smerfs - [master] » 
```

**Comment by pec27** [comment]
Ah, a python 3 user, very progressive!

**Comment by pec27** [comment]
Can you pull the latest change and try (works on my python 3.5.1 setup)?

**Comment by sjsrey** [comment]
Works great locally after pulling from master.
